apiVersion: argoproj.io/v1alpha1              # Указывает версию API ArgoCD, используемую для этого ресурса (v1alpha1).
kind: Application                             # Определяет тип ресурса — Application, объект для управления приложением в ArgoCD.
metadata:                                     # Секция метаданных для идентификации объекта.
  name: myapp1                                # Имя приложения в ArgoCD, здесь "myapp1" — уникальное имя приложения.
  namespace: argocd                           # Пространство имен, где создается этот ресурс (argocd — стандартное для ArgoCD).
  finalizers:                                 # Список финализаторов, выполняемых перед удалением ресурса.
  - resources-finalizer.argocd.argoproj.io    # Финализатор ArgoCD для корректной очистки ресурсов при удалении.
spec:                                         # Спецификация желаемого состояния приложения.
  destination:                                # Указывает целевой кластер и пространство имен для развертывания.
    name: in-cluster                          # Имя целевого кластера, "in-cluster" — локальный кластер с ArgoCD.
    namespace: app1                           # Целевое пространство имен для приложения (app1 — пользовательское пространство).
  source:                                     # Описывает источник конфигурации приложения.
    path: "demo/HelmCharts/Chart1"            # Путь URL Git-репозитория, где находится Helm-чарт для этого приложения.
    repoURL: "git@github.com:PetrovEvgenyS/argocd.git"  # Путь в репозитории до нужного каталога с манифестами (SSH-формат).
    targetRevision: HEAD                      # Ветка, тег или коммит, из которого брать манифесты. HEAD — последняя версия ветки.
    helm:                                     # Настройки для Helm-чарта, используемого в приложении.
      valueFiles:                             # Список файлов с значениями для Helm.
      - values.yaml                           # Указывает файл values.yaml для переопределения параметров Helm-чарта.
      parameters:                             # Список параметров, переопределяющих значения Helm-чарта.
      - name: "image.tag"                     # Имя параметра Helm, здесь "image.tag" — тег образа контейнера.
        value: v1.1                           # Значение параметра, здесь "v1.0" — конкретный тег образа.
  project: default                            # Имя проекта ArgoCD, к которому привязано приложение (default — стандартный проект).
  syncPolicy:                                 # Политика синхронизации приложения.
    automated:                                # Включает автоматическую синхронизацию.
      prune: true                             # Разрешает удаление ресурсов, отсутствующих в репозитории.
      selfHeal: true                          # Включает самовосстановление при расхождениях состояния.
    syncOptions:                              # Дополнительные опции синхронизации.
      - CreateNamespace=true                  # Указывает ArgoCD создать пространство имен (app1), если его нет.
