apiVersion: argoproj.io/v1alpha1  # Указываем версию API, которую использует ArgoCD для ресурса Application.
kind: Application                 # Указываем тип ресурса — Application (приложение ArgoCD).
metadata:                         # Метаданные приложения.
  name     : root                 # Задаем имя приложения — "root".
  namespace: argocd               # Указываем namespace, где будет развернуто приложение.
  finalizers:
  - resources-finalizer.argocd.argoproj.io  # Финализатор — предотвращает удаление Application до удаления всех зависимых ресурсов.
spec:                             # Основная спецификация, определяющая поведение приложения.
  destination:                    # Описание места назначения (куда будет применяться манифест из Git).
    name     : in-cluster         # Указывает, что ресурсы будут применяться в текущем (in-cluster) кластере.
    namespace: argocd             # Namespace, куда будут развернуты ресурсы из Git.
  source:                               # Описание источника (откуда ArgoCD будет забирать манифесты).
    repoURL       : "${repoURL}"        # URL Git-репозитория (подставляется из переменной).
    path          : "${path}"           # Путь в репозиторий до нужного каталога с манифестами (подставляется из переменной).
    targetRevision: "${targetRevision}" # Ветка, тег или коммит, из которого брать манифесты (подставляется из переменной).
  project: default                      # Название проекта ArgoCD, в рамках которого будет создано приложение (по умолчанию — "default").
  syncPolicy:                           # Определяет стратегию синхронизации (как ArgoCD применяет изменения из Git).
    automated:                          # Включение автоматической синхронизации.
      prune   : true                    # Автоматически удаляет ресурсы, которых больше нет в Git (чистка "мусора").
      selfHeal: true                    # Автоматически исправляет ресурсы, если они изменены вручную в кластере (восстанавливает Git-состояние).
