apiVersion: argoproj.io/v1alpha1              # Указывает версию API ArgoCD, (v1alpha1 — стабильная версия).
kind: Application                             # Определяет тип ресурса — Application, объект ArgoCD для управления приложениями.
metadata:                                     # Секция метаданных, содержит идентификационные данные объекта.
  name: root                                  # Имя приложения в ArgoCD, в данном случае "root" — корневое приложение.
  namespace: argocd                           # Пространство имен, где будет создан этот ресурс (argocd — стандартное пространство для ArgoCD).
  finalizers:                                 # Список финализаторов, которые выполняются перед удалением ресурса.
  - resources-finalizer.argocd.argoproj.io    # Финализатор ArgoCD, гарантирует очистку связанных ресурсов при удалении приложения.
spec:                                         # Спецификация, описывающая желаемое состояние приложения.
  destination:                                # Указывает, куда будет развернуто приложение.
    name: in-cluster                          # Имя целевого кластера, "in-cluster" означает локальный кластер, где установлен ArgoCD.
    namespace: argocd                         # Целевое пространство имен для развертывания приложения (в данном случае argocd).
  source:                                     # Описывает источник конфигурации приложения (репозиторий и путь).
    path: "demo/AppOfApp/applications"        # Путь в репозитории, где находятся манифесты или Helm-чарты для этого приложения.
    repoURL: "git@github.com:PetrovEvgenyS/argocd.git"  # URL Git-репозитория, откуда ArgoCD берет конфигурацию (SSH-формат).
    targetRevision: HEAD                      # Целевая ревизия Git, HEAD означает последнюю версию ветки по умолчанию.
  project: default                            # Имя проекта ArgoCD, к которому относится это приложение (default — встроенный проект).
  syncPolicy:                                 # Политика синхронизации приложения с репозиторием.
    automated:                                # Включает автоматическую синхронизацию.
      prune: true                             # Разрешает удаление ресурсов, которые больше не присутствуют в репозитории (очистка).
      selfHeal: true                          # Разрешает автоматическое исправление расхождений между желаемым и текущим состоянием.